name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcc 32bits support
      run: sudo apt-get install gcc-multilib g++-multilib libgtest-dev
    - name: Install googletest 
      run: "cd /usr/src/gtest && cmake CMakeLists.txt && make && sudo cp *.a /usr/lib"
    - name: setup
      run: ./setup.sh
    - name: make
      run: make
